In [1]:
import numpy as np
import sys
import math


In [3]:
# global variable to denote the number of row and col in game board
TOTAL_ROW_COUNT = 6
TOTAL_COL_COUNT = 7


# function to initialize the game board
def make_board():
    # using numpy fill a 6x7 with zeros as a board
    board = np.zeros((TOTAL_ROW_COUNT, TOTAL_COL_COUNT))
    # return created board
    return board


def print_board(board):
    print(np.flip(board, 0))


if __name__ == "__main__":
    game_board = make_board()
    print_board(game_board)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
